name: CI Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.11-slim

    # Required services
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --system --dev

      - name: Run flake8 and pylint
        run: |
          echo "Running flake8 (fatal checks)..."
          flake8 service tests --count --select=E9,F63,F7,F82 --show-source --statistics
          echo "Running flake8 (style/complexity)..."
          flake8 service tests --count --max-complexity=10 --max-line-length=127 --statistics
          echo "Running pylint..."
          pylint service tests --max-line-length=127

      - name: Run unit tests
        run: pytest --pspec --cov=service --cov-fail-under=95
        env:
          DATABASE_URI: "postgresql+psycopg://postgres:postgres@postgres:5432/testdb"


      ######################################################################
      # Create a CODECOV_TOKEN in Settings->Secrets and variables->Actions
      # and then uncomment the CodeCov action during hands-on lab
      ######################################################################

      - name: Install packages for Codecov to work
        run: apt-get update && apt-get install -y git curl gpg

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: CSCI-GA-2820-FA25-001/wishlists